### PR TITLE
Pull request for my fork of pillbox

### PR DESCRIPTION
**Pull request by kgautreaux**
Hi David, et al.

I'm sending my first pull request for my version of pillbox_resource.  I've made quite a few changes including some changes to the structure to make it more 'gem'-like.  I wonder if maybe we shouldn't break it out into a Ruby wrapper and a Python wrapper that are separate so it can be installed as a gem.

Issues with this release:
- The tests actually hit the API

In the beta I don't think this is a big deal because everyone should have an API key personally assigned and these can be pulled if someone is abusive.  Long term I hope to fix this with something like FakeWeb.  Suggestions welcome.
- Test coverage is not 100%
- Should be compatible on 1.8.7 and 1.9.2 with ActiveResource 2.3.\* or 3.0.*

In the future I would like to test this more thoroughly.
- Some formatting changes might break the Facebooker sample app.

I couldn't get it to run without some tweaking and then I don't use facebook so it keep erroring.  Could someone test if it breaks the app and file an issue so I can fix it?
- It prints out the options hash

I think this is helpful for understanding the API but it can be commented out if anyone does not like it.

Let me know if I messed something up and need to resubmit.  Thanks a bunch.

### CODE REVIEW

**Comment by ghost** [comment]
Keith,

Not sure how I can pull these commits.  I don't have any of the code locally.

Can I add you as a collaborator?

**Comment by kgautreaux** [comment]
Probably.  I think if you add me as a collaborator through the admin interface for the pillbox repo then I can merge my changes with the master branch on my machine and just push to your repo to make the changes.

Of course that would change the directory structure somewhat.  Maybe you just want me to create a new repo with only the ruby wrapper?

**Comment by ghost** [comment]
What do you think would be the most logical solution? Is is better to change the structure somewhat and not have others looking across different repos, or keep this branch as is and have another repo?

**Comment by kgautreaux** [comment]
My personal preference would be to have separate repos for the Ruby and Python wrappers. I think the advantages of this would be several fold. 

1.) Only the code you want - i'm usually looking for a library in a specific language so if I download the ruby repo I don't necessarily want Python in it and vice versa.

2.) Github searching - Github allows you to filter your search by language. Separate repos would make things less confusing for searches. 

3.) Gem creation - Creating a gem from the Ruby wrapper would be a lot easier if the repo was structured like a gem and there weren't Facebook demo apps and python libs in the directory structure. 

I'm totally open to simply creating a new ( non-forked) repo with the Ruby wrapper named something like Pillboxr and just hosting it as a public repo under my account and submitting it periodically to rubygems.org when changes are made. It might be nice to have a pointer from the original repo or from the Pillbox site for devs looking for a wrapper library, though.

**Comment by ghost** [comment]
Ok, sounds good. Thanks!

Can we link to your repo from here?

**Comment by kgautreaux** [comment]
I'll create a new repo over this coming weekend and populate it with my updated code.  Maybe you can just remove the ruby portion from pillbox proper and link to the new repo in the README or something.  I'll let you decide how you want to do it since it's your project.

I'll make sure to send you updated links for the repo and any gems I create from it so people know where to go for the most up to date ruby wrapper.

**Comment by jdar** [comment]
Hi Keith!

Sorry -- I'm just NOW reading this thread, and looking over your code organization. Looks great!

That sounds perfect, and logical, especially gemifying, which I didn't have any experience with at the time of the hackathon. I spoke briefly with the python guy, Chris, and he's in agreement as well about a separate python egg.

I'll take down the code and make the readme a link to your 'pillbox' until you create 'pillboxr'. After the whistle blows tho, so I'm not doing it from my day job's computer.

D

**Comment by jdar** [comment]
I just realized... it doesn't actually take any time to _delete_ code.... only to write it.

PUSHED.

**Comment by kgautreaux** [comment]
I renamed my forked repo to pillboxr, removed the python and the facebook app, renamed a bunch of constants and regenerated the documentation and pushed it to the 'activeresource3' branch of my pillboxr repo.  If everything looks okay to you guys I'll merge it into the master branch of that repo and then make a Gem this weekend.

Long winded way of saying you can update the pillbox repo README to point to http://github.com/kgautreaux/pillboxr.  Thanks guys.

**Comment by kgautreaux** [comment]
Just to close this out.

The gem is now available with a simple 'gem install pillboxr', and the documentation has been generated at http://rdoc.info/github/kgautreaux/pillboxr/master/frames

**Pull request closed without merging**
